# Copyright 2022 Google LLC
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#      http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

apiVersion: v1
kind: Namespace
metadata:
  name: logging-system
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: fluentbit-user
  namespace: logging-system
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: fluentbit-user
rules:
- apiGroups:
  - ""
  resources:
  - nodes
  - pods
  - namespaces
  verbs:
  - watch
  - get
  - list
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: fluentbit-user
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: fluentbit-user
subjects:
- kind: ServiceAccount
  name: fluentbit-user
  namespace: logging-system
---
# The token minter sidecar needs permission to create a token for
# logging-system/fluentbit-user
apiVersion: v1
kind: ServiceAccount
metadata:
  namespace: logging-system
  name: user-telemetry-agent
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: fluentbit-token-minter
  namespace: logging-system
rules:
- apiGroups:
  - ''
  resources:
  - serviceaccounts/token
  resourceNames:
  - user-telemetry-agent
  verbs:
  - create
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: fluentbit-token-minter
  namespace: logging-system
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: fluentbit-token-minter
subjects:
- kind: ServiceAccount
  name: fluentbit-user
  namespace: logging-system